version: "3.9"
services:

  client:
    network_mode: host
    build: ./client
    depends_on:
      - server
    
  server:
    network_mode: host
    build: ./server
    ports:
      - "50051:50051"